### ISSUE TITLE
Thanks for being good citizens!

### ISSUE THREAD

**Issue by bombardier-gif** [pallupz/covid-vaccine-booking#124]
I understand many people looked down upon such bots. I personally prefer this current Human Vs Human situation with captcha than the Human Vs Bot situation before.

But overall the booking system has been flawed in the first place. I was able to get a slot myself manually by quick response, and with time it got more and more difficult for my friends and family. Online booking itself is exclusionary (my dad would have never been able to book by himself).

What I liked about this project was that it was shared with the community to be used, many people built on top of it, fixed bugs and made it better (someone could have kept the tool for themselves and this would have never been addressed).

Cheers for the mindset to serve the community. I have seen people get a slot with this tool who never would have gotten one manually. 

Stay safe! 

Note: I would request the owner of this repo to pin this so that people could read the positive intentions behind this project.

**Comment by pallupz** [comment]
> Note: I would request the owner of this repo to pin this so that people could read the positive intentions behind this project.

For sure, paints me in a good a light lol.

Although this isn't completely over - only auto booking is: https://github.com/pallupz/covid-vaccine-booking/issues/123#issuecomment-834241919

**Comment by pallupz** [comment]
To be clear - it's over for this repo, at least for now

**Comment by anilaphale** [comment]
I have some solution for captcha. author please share your email we can discuss.

**Comment by mrms123** [comment]
Over the last 2 hours, a lot of my non-tech-savvy friends got appointments (Delhi was releasing appointments when the captcha was implemented). I guess it shows how the whole system was being saturated by bots.

That said, I think the booking system should change. Probably like the course bidding system we have in colleges - or maybe even simpler, a preference list. 

- Users define their preferred centers, and the preferred dates (or an option to have an any date), free/paid/any.
- Maintain this queue as a doubly linked list (we will be removing elements from the middle often)
- Whenever we have a new registration / preference defined, add that user to the end of the queue. If required, have separate queue for priority groups (45+ is one queue, 18-44 is another; can have overdue second dose as another queue)
- Take all available appointments open only to 45+ - go through the queue, and allot them based on top preference order
- Once this is done, take all appointments open to 18+ - go through the queue and allot them in the same fashion

All centers can be asked to upload availability by a given time - say 5PM. Allotment can be run at 7PM, and people can be intimated via SMS.

The challenge here is the scale, and how to be efficient for a billion population

**Comment by archit-va** [comment]
> I have some solution for captcha. author please share your email we can discuss.

why dont you do it yourself and share with us( or talk to the developer in his linkedin)

**Comment by Walkie913** [comment]
@anilaphale Keep your codes with youself and let others to book. Please dont act selfish in this pandemic. Use your skills to help the community in a legal way

**Comment by pallupz** [comment]
@Walkie913 if it is possible, someone somewhere will be doing it. no point in berating @anilaphale

If it's happening out in the open, authorities will notice

**Comment by anilaphale** [comment]
> @anilaphale Keep your codes with youself and let others to book. Please dont act selfish in this pandemic. Use your skills to help the community in a legal way

that's what the plan is help community. but before implementing anything wanted to discuss with author get his suggestion as well.

**Comment by harishvishwakarma** [comment]
Is it a Captcha? If yes, just open it and let the user type it on terminal.

**Comment by pallupz** [comment]
link to discord server if anyone's interested in a single place for discussions : https://discord.gg/rCz8VdRB

**Comment by axd123** [comment]
First, kudos to @pallupz @bombardier-gif  and others who have tried to code around the flawed system we are enduring. 

Here are my views on this.

It may be unfair by some peoples' perspectives, but remember this is being done as free-to-use open source project, and not a money-grabbing app on the playstore. Infact their code implementations help the "non-coders" still make use of a better system to fair degree. Personally, I have managed to book slots for a number of people who have been struggling to get one for the past week - these are "non tech savvy" friends and people who don't have access to laptops such as domestic helps and support staffs.

Anyone who feels that any use of code is unfair should look to the ones _that made the flawed system_, not the ones who leveraged it to their advantage (_and frankly to everyone elses'_). 

**The issue is in the way the system itself is implemented.** 
It requires constant engaging of the user, causes server crashes, and spawned the dystopian version of fastest-fingers-first that we have all come to experience this past week.

Instead of this logging in and booking on your own system, the implementation should have been something along these lines:
1. User registers on the official website
2. User inputs relevant beneficiary details (as they do now)
3. User selects preferred vaccination centres (depending on their location/mobility/time/monetary constraints and requirements) and confirms the same using an otp, resulting in a token being assigned against the beneficiary.
4. Based on the token (FIFO), the system self assigns slots on the users' preferences as and when the slots are updated by the hospital.
5. Once a viable slot is assigned to the user, they are notified by sms/email/robocall. 
6. The user can log into the official portal and confirm the assigned slot. If the slot doesn't work for them for whatever reason, the can cancel it, so it can be assigned to the next portal. 

The only cons I can think of the above approach would be double booking, which frankly is still an issue with the current system and is inevitable since eliminating it would require some implementation of digilocker/aadhar verification that not everyone has access to in some form or the other.
Another one might be wastage of assigned slots that people dont show up for, which could be easily stemmed by post-slot-assignment verification where the user needs to explicitly confirm the assigned slots within a reasonable span of buffer time, otherwise it moves to the next token in line. 

This approach, in my view, could potentially cut the number of users trying to login at specific times and overloading the servers (which eventually result in crashing of the otp generation etc). It would also eliminate the fastest finger first non-sense, and use automation that they have obviously not taken full advantage of.

**Comment by Walkie913** [comment]
Good arguments for gaming the system😂😂..
