### ISSUE TITLE
403 Forbidden error again

### ISSUE THREAD

**Issue by bitshiftr** [pallupz/covid-vaccine-booking#82]
Looks like they have changed something again. Here is the error I am getting:

Unable to Create OTP
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>

**Comment by pallupz** [comment]
oh man!

**Comment by sixfooter** [comment]
yes, its changing , https://github.com/pallupz/covid-vaccine-booking/issues/80#issuecomment-833438143

**Comment by bitshiftr** [comment]
Cowin site itself seems to be non functional

**Comment by sixfooter** [comment]
this time, its with the first step of sending the OTP .
Cowin seems to still work.

**Comment by bitshiftr** [comment]
and we are back again!

**Comment by Sidbeheraunsw** [comment]
Is it working for you guys ?

**Comment by pallupz** [comment]
yea its working but its spotty. not a good sign.

**Comment by Sidbeheraunsw** [comment]
I could use it tomorrow but today I am not able to book

**Comment by pallupz** [comment]
if they add a captcha, that will be game over

**Comment by sixfooter** [comment]
its up again but it keeps getting tapped out once in a while. 
While i dont think the script has an issue but the destination is changing sthg in between.

**Comment by AmoghDabholkar** [comment]
Yup working fine for now but need to get to the bottom of this

**Comment by pallupz** [comment]
I will keep this open. Otherwise people will keep creating issues.

**Comment by Sidbeheraunsw** [comment]
Thanks brother for your efforts

**Comment by pallupz** [comment]
If this script was useful, please feel free to spread the word a bit - if you don't mind. Link: https://www.linkedin.com/feed/update/urn:li:activity:6794138228464193536/

**Comment by AmoghDabholkar** [comment]
BITSians ftw!

**Comment by pallupz** [comment]
Hahaha.. I did their online course - not a "pure bred" BITSian I guess

**Comment by AmoghDabholkar** [comment]
Still, lovely job with this one, appreciate it!

**Comment by tanmecolor** [comment]
> Looks like they have changed something again. Here is the error I am getting:
> 
> Unable to Create OTP
> <title>403 Forbidden</title>
> # 403 Forbidden

the rate limit for the api is 100 calls every  5 minutes from an IP , so when you schedule the scan for slots it would be better if you can increase the time between each scans, since the script takes values in seconds and the minimum being 5 seconds , it would be good that you increase the value to  120 seconds  or  in multiples of 60 . This would prevent the server from red flagging the IP (also prevent abuse) .

**Comment by mrms123** [comment]
The issue is if you have a CGNAT IP - many users on your network have the same IP.  The rate limiting calculations will have to accommodate that, as more and more people start using scripts.

https://www.remoterig.com/wp/?page_id=3494
https://techenclave.com/threads/isp-in-bangalore-without-cgnat.189602/

**Comment by XtremePwnership** [comment]
> the rate limit for the api is 100 calls every 5 minutes from an IP , 

@tanmecolor Is there any official ratelimits page?

**Comment by pallupz** [comment]
no, I just used developer mode on browser to get it.. fortunately it works in most cases

**Comment by pallupz** [comment]
until they stop it, that is
